random_seed = 1

[volume]
resolution = [1, 1, 1]

[model]
input_fov_shape = [33, 33, 33]
output_fov_shape = [33, 33, 33]
output_fov_move_fraction = 4
training_subv_shape = [49, 49, 49]
validation_subv_shape = [49, 49, 49]
input_channels = 3
v_true = 0.95
v_false = 0.05
t_move = 0.9
move_check_thickness = 1
move_recheck = true

[network]
factory = 'diluvian.network.make_flood_fill_network'
num_modules = 8
convolution_dim = [3, 3, 3]
convolution_filters = 32
output_activation = "sigmoid"
initialization = "glorot_uniform"
dropout_probability = 0.05
unet_num_layers = 4
unet_downsample_rate = [0, 1, 1]

[optimizer]
klass = "Adam"
lr = 0.001
momentum = 0.5
nesterov = true

[training]
gpu_batch_size = 8
num_gpus = 1
num_workers = 4
training_size = 1024
validation_size = 256
total_epochs = 3
reset_generators = false
# fill_factor_bins = [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075,
#                     0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
partitions = {".*" = [1, 1, 1]}
training_partition = {"^(?!(0016|0017))" = [0, 0, 0]}
validation_partition = {"^(0016|0017)" = [0, 0, 0]}
patience = 4
label_erosion = []
augment_use_both = false
augment_missing_data = []
augment_mirrors = [0,1,2]
augment_noise = []
augment_permute_axes = [[2,1,0], [1,0,2], [1,2,0]]
augment_contrast = []
augment_permute_channels = true
augment_density = true
test_regex = "^(0018|0019)"
train_regex = "^(?!(0018|0019))"

[postprocessing]
